### ISSUE TITLE
Adding a commit-msg node script results in failing commits on Windows

### ISSUE THREAD

**Issue by mburmistrov** [evilmartians/lefthook#975]
### :wrench: Summary

When performing a commit on Windows having a simple `commit-msg` node script, the commit fails with an error.
It seems like something in the building script path process is broken. The problem repoduced on at least 3 different PCs.
The script setup is like this
```
commit-msg:
  scripts:
    "hello-world.js":
      runner: node
```
All the details are below, could you please check? Thank you!

### Lefthook version
Tested on 1.11.3 9ee6a56928e128cc224a713c228aca9f145fadd6. 

The issue also reproduces in v1.7.16 and v1.8.0. Works fine on v1.7.15.

### Steps to reproduce
Here is a demo repository.
https://github.com/mburmistrov/lefthook-windows-script-path-issue

Reproduction steps:  

**Step 0:** Use Windows (tested in PowerShell on Windows 10 x64). 

**Step 1:** Clone the repository. 

**Step 2:** Run `npm install`.

**Step 3:** Try to commit a change, e.g.  
```bash
echo hi >> example
git add example
git commit -m 'Test commit'
``` 

### Expected results

Successful commit with a message `Hello world!` from Lefthook.

![Image](https://github.com/user-attachments/assets/aab782c8-793f-468b-9f55-e532db341254)

### Actual results

Error like below instead of a successful commit.
```
Error: Cannot find module 'C:\Users\mmb\lefthook-windows-script-path-issue\'C:\Users\mmb\lefthook-windows-script-path-issue\.lefthook\commit-msg\hello-world.js''
at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
at Module._load (node:internal/modules/cjs/loader:1043:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
at node:internal/main/run_main_module:28:49 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}

Node.js v20.19.0
┃  hello-world.js ❯


exit status 1
────────────────────────────────────
summary: (done in 0.10 seconds)
```

![Image](https://github.com/user-attachments/assets/d4c2dc0b-8b0b-45c5-a306-c4c6e0860e16)

### Logs / Screenshots

Log are here: https://github.com/mburmistrov/lefthook-windows-script-path-issue/blob/main/verbose-log.txt

**Comment by mrexox** [comment]
Hey! Thank you for creating this issue. I've released a fix in lefthook 1.11.5. Could you please check if the issue still reproduces?

**Comment by mburmistrov** [comment]
Everything works as intended now, many thanks for a quick fix! 🙏
