### ISSUE TITLE
Error: Cannot find module 'lefthook-linux-x64/bin/lefthook' on git commit after updating npm dependency to 1.6.10

### ISSUE THREAD

**Issue by alexandrulesi** [evilmartians/lefthook#708]
### :wrench: Summary

In an npm environment after updating lefthook to `1.6.10` package version I am no longer able to make commits on my Fedora Linux 39 Workstation machine. I don't have the issue on `1.6.8`.

I'm also not seeing any of these packages mentioned in the package lock in the node_modules folder:
```
  "packages": {
    ...
    "node_modules/lefthook": {
      "optionalDependencies": {
        "lefthook-darwin-arm64": "1.6.10",
        "lefthook-darwin-x64": "1.6.10",
        "lefthook-freebsd-arm64": "1.6.10",
        "lefthook-freebsd-x64": "1.6.10",
        "lefthook-linux-arm64": "1.6.10",
        "lefthook-linux-x64": "1.6.10",
        "lefthook-windows-arm64": "1.6.10",
        "lefthook-windows-x64": "1.6.10"
      }
    }
  }
```

### Lefthook version

 package.json dependency version `1.6.10`. Trying to call `npx lefthook version -f` throws the same error mentioned below.

### Steps to reproduce

1. Upgrade dependency version to `1.6.10`
2. `npm i`
3. Try to make any commit

### Expected results

Successful commit

### Actual results

Error: Cannot find module 'lefthook-linux-x64/bin/lefthook'

### Logs / Screenshots

```bash
+ '[' '' = 0 ']'
+ call_lefthook run prepare-commit-msg .git/COMMIT_EDITMSG message
++ git rev-parse --show-toplevel
+ dir=/home/redacted
++ uname
++ tr '[:upper:]' '[:lower:]'
+ osArch=linux
++ uname -m
++ sed s/aarch64/arm64/
+ cpuArch=x86_64
+ test -n ''
+ lefthook -h
+ test -f /home/redacted/node_modules/lefthook/bin/index.js
+ /home/redacted/node_modules/lefthook/bin/index.js run prepare-commit-msg .git/COMMIT_EDITMSG message
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'lefthook-linux-x64/bin/lefthook'
Require stack:
- /home/redacted/node_modules/lefthook/get-exe.js
- /home/redacted/node_modules/lefthook/bin/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:127:19)
    at getExePath (/home/redacted/node_modules/lefthook/get-exe.js:17:18)
    at Object.<anonymous> (/home/redacted/node_modules/lefthook/bin/index.js:9:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/redacted/node_modules/lefthook/get-exe.js',
    '/home/redacted/node_modules/lefthook/bin/index.js'
  ]
}

Node.js v18.17.1
```

**Comment by flntzr** [comment]
The same applies to a MacBook Pro with an M3 Pro on macOS Sonoma.

```
Error: Cannot find module 'lefthook-darwin-arm64/bin/lefthook'
Require stack:
- /Users/difflint/workspace/exampleProject/node_modules/lefthook/get-exe.js
- /Users/difflint/workspace/exampleProject/node_modules/lefthook/bin/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at getExePath (/Users/difflint/workspace/exampleProject/node_modules/lefthook/get-exe.js:17:18)
    at Object.<anonymous> (/Users/difflint/workspace/exampleProject/node_modules/lefthook/bin/index.js:9:5)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/difflint/workspace/exampleProject/node_modules/lefthook/get-exe.js',
    '/Users/difflint/workspace/exampleProject/node_modules/lefthook/bin/index.js'
  ]
}
```

**Comment by mrexox** [comment]
Hey! Do you skip installation of `optionalDependencies`? Could you share the way you install lefthook? It should usually go to `devDependencies`.

Since 1.6.8 there was nothing special added to package management.

**Comment by flntzr** [comment]
I am not entirely sure what happened here but after another `npm install` it seems to be working with 1.6.10 as well. I did not skip any `optionalDependencies` and lefthook is part of the `devDependencies`.

The project in question is a monorepo using npm workspaces in combination with lerna and I suspect this has introduced some flakiness since we've seen a similar issue before. If it's relevant, it previously occurred with `lightningcss-linux-arm64-gnu`.

@alexandrulesi Do you have a similar project setup, i.e. lerna and/or npm workspaces could be to blame?

**Comment by flntzr** [comment]
I believe this is related to [this bug](https://github.com/npm/cli/issues/4828) in the npm CLI and can be closed here.

**Comment by JeffJacobson** [comment]
I've had a similar issue on Windows 10 (but with a slightly different, windows-related error message, obviously).

Reverting to previous version fixed the issue.

Perhaps its related to #722, about virus scanners detecting the latest lefthook as a virus. Windows Security did warn me about an issue today, which went away after reverting to the previous version of lefthook.

I don't remember upgrading lefthook TODAY, when I started seeing problems, which is why I think it might be related to #722.

Partial package.json below, post reversion. (I'm sure anyone reading this would already understand how to revert to an early version, but just in case...)

```json
"devDependencies": {
    "lefthook": "1.6.11",
}
```

**Comment by mrexox** [comment]
Hey! Does the issue still persist with the lefthook v1.6.16?

**Comment by thoroc** [comment]
Just got a similar error on a macos x64 and version `^1.6.18`
```sh
Cannot find module 'lefthook-darwin-x64/bin/lefthook'
```

So I'd say yes.

**Comment by mrexox** [comment]
What package manager do you use?

**Comment by IsmaelMartinez** [comment]
I had a similar issue but it was related to the upgrade of husky to 9.x https://github.com/typicode/husky/releases/tag/v9.0.1 . They deprecated the `husky install` command (just remove the install). Without that change, nothing gets installed but the npm i (or others) looks like it completes without errors (what is not the case, as it just doesn't do the installs)

Maybe it helps others.

**Comment by thoroc** [comment]
> What package manager do you use?

I was personally using `npm` (tried `pnpm` as well fwiw) when that happened

**Comment by mrexox** [comment]
@thoroc do you still have this issue with the latest versions of lefthook? I remember there were issues with packaging some time ago because we were trying to fix the issue for `bun` environment. But the problem must be fixed, could you verify this?

**Comment by mrexox** [comment]
@garrettg123 , could you share the logs? Is the issue the same as in the description?

**Comment by mrexox** [comment]
Hey guys! Does the issue reproduce on latest version 1.10.5?

**Comment by chanwukim** [comment]
> Hey guys! Does the issue reproduce on latest version 1.10.5?

I have the same problem when deploying to vercel.

`"lefthook": "^1.10.10",`

```
[16:07:34.362] Running build in Washington, D.C., USA (East) – iad1
[16:07:34.491] Cloning github.com/chanwukim/stamp-duty-web (Branch: refactor, Commit: c5c66fd)
[16:07:35.592] Cloning completed: 1.104s
[16:07:36.825] Restored build cache from previous deployment (8taa78e4cZYeSAt3ZEG1MPd4rYF4)
[16:07:36.894] Running "vercel build"
[16:07:37.257] Vercel CLI 41.1.4
[16:07:37.809] Installing dependencies...
[16:07:40.068] 
[16:07:40.069] > project-name@0.0.0 prepare
[16:07:40.069] > lefthook install
[16:07:40.069] 
[16:07:40.104] node:internal/modules/cjs/loader:1228
[16:07:40.105]   throw err;
[16:07:40.105]   ^
[16:07:40.105] 
[16:07:40.105] Error: Cannot find module 'lefthook-linux-x64/bin/lefthook'
[16:07:40.105] Require stack:
[16:07:40.105] - /vercel/path0/node_modules/lefthook/get-exe.js
[16:07:40.106] - /vercel/path0/node_modules/lefthook/bin/index.js
[16:07:40.106]     at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
[16:07:40.106]     at Function.resolve (node:internal/modules/helpers:146:19)
[16:07:40.108]     at getExePath (/vercel/path0/node_modules/lefthook/get-exe.js:17:18)
[16:07:40.108]     at Object.<anonymous> (/vercel/path0/node_modules/lefthook/bin/index.js:9:5)
[16:07:40.108]     at Module._compile (node:internal/modules/cjs/loader:1554:14)
[16:07:40.108]     at Object..js (node:internal/modules/cjs/loader:1706:10)
[16:07:40.108]     at Module.load (node:internal/modules/cjs/loader:1289:32)
[16:07:40.109]     at Function._load (node:internal/modules/cjs/loader:1108:12)
[16:07:40.109]     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
[16:07:40.109]     at wrapModuleLoad (node:internal/modules/cjs/loader:220:24) {
[16:07:40.109]   code: 'MODULE_NOT_FOUND',
[16:07:40.114]   requireStack: [
[16:07:40.114]     '/vercel/path0/node_modules/lefthook/get-exe.js',
[16:07:40.114]     '/vercel/path0/node_modules/lefthook/bin/index.js'
[16:07:40.114]   ]
[16:07:40.114] }
[16:07:40.115] 
[16:07:40.115] Node.js v22.14.0
[16:07:40.119] npm error code 1
[16:07:40.119] npm error path /vercel/path0
[16:07:40.119] npm error command failed
[16:07:40.119] npm error command sh -c lefthook install
[16:07:40.121] npm error A complete log of this run can be found in: /vercel/.npm/_logs/2025-02-24T07_07_38_032Z-debug-0.log
[16:07:40.154] Error: Command "npm install" exited with 1
[16:07:40.484] 
```

**Comment by mrexox** [comment]
Do you have `lefthook-linux-x64` in `node_modules`?

**Comment by Shurtu-gal** [comment]
We are having the same problem:
 Error: Cannot find module 'lefthook-linux-x64/bin/lefthook'

**Comment by thoroc** [comment]
@mrexox apologies for not replying before; I somehow missed the notifications. I think I eventually nuked the `node_modules` directory and installed again. Never reared it heads as far as I am concerned. I appreciate this isn't very useful, but I still wanted to provide feedback (even if is it more than belated).

FWIW: I am using lefthook daily as the git hook manager on countless projects (both on Node and _not_ Node based)

**Comment by FDiskas** [comment]
The same issue exists on GitHub Actions. We are avoiding `npm install` because of recent vulnerabilities in patched npm packages.
```yml
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund
```
We install dependencies like that. So that means NPM will strictly follow the lock file. As a developer (on windows os), I push a lock file depending on my machine, which is probably why I don't have a Linux bin variant module.
Probably a similar issue was documented https://nextjs.org/docs/messages/failed-loading-swc 
So they do have a workaround - I do notice sometimes a warning that some binaries are missing and they are added automaticly to the lock file. You can see how they solved a similar issue
https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/patch-incorrect-lockfile.ts#L39

~~The question: how can I avoid installing `lefthook` on CI?~~
https://lefthook.dev/usage/env.html?highlight=CI#ci

Ok my message is invalid. In package.json we have
```
    "prepare": "npx lefthook install"
```
So this is invalid

**Comment by JeffLoo-ong** [comment]
Sharing what worked for me here for my local branch as I was beating my head over this several times. 

Option 1: Update node version. I was using Node v20.XX and updating originally fixed the problem for me. 

It reared its head again after I mistakenly deleted my yarn.lock file and did a yarn install again (I bet the files installed were not set for the M1 mac's architecture)


Option 2: do the following: 

-- remove installs & lock
rm -rf node_modules
rm -f yarn.lock

-- clear Yarn’s classic cache (the v6 path in your warning confirms Yarn v1)
yarn cache clean
rm -rf ~/Library/Caches/Yarn/v6

-- reinstall on ARM so it picks lefthook-darwin-arm64
yarn install
