### ISSUE TITLE
Error: Cannot find module 'lefthook-darwin-arm64/bin/lefthook' in 1.11.14 for mac

### ISSUE THREAD

**Issue by wuhaohuang** [evilmartians/lefthook#1046]
### :wrench: Summary

When upgrading to 1.11.14, an error is reported when executing the lefthook command (Cannot find module 'lefthook-darwin-arm64/bin/lefthook'), but it can be executed normally after downgrading to 1.11.13

mbp M3 Max

**Comment by mrexox** [comment]
Hey @wuhaohuang , do you have `node_modules` in your project? Or maybe you are using another linker?

**Comment by codeusb** [comment]
It's the same on my M1

**Comment by corrigancd** [comment]
Perhaps unrelated, but I'm getting checksum errors on v1.11.14, and all is working when I rolled back to v1.11.13

I'm using WSL

**Comment by mrexox** [comment]
> getting checksum errors on v1.11.14

Could you provide some logs?

**Comment by wuhaohuang** [comment]
> Hey [@wuhaohuang](https://github.com/wuhaohuang) , do you have `node_modules` in your project? Or maybe you are using another linker?

Yes, I have node_module, and I have checked and confirmed that there is a lefthook directory, but executing the command gives an error

**Comment by mrexox** [comment]
@wuhaohuang what’s in the node_modules/lefthook? Ideally it should have the following:

```
tree node_modules
node_modules
├── lefthook
│   ├── README.md
│   ├── bin
│   │   └── index.js
│   ├── get-exe.js
│   ├── package.json
│   ├── postinstall.js
│   └── schema.json
└── lefthook-darwin-arm64
    ├── README.md
    ├── bin
    │   └── lefthook <- the binary
    └── package.json
```

If there’s no `lefthook-darwin-arm64`, could you check if you have

```
omit=optional
```

In your ~/.npmrc?

Also does this fix the issue: `npm install —include=optional`?

### Why?

`lefthook` NPM package distributes all os+arch packages as optional, so the system installs the one with matching OS and architecture. If you omit an optional packages nothing will be installed.

**Comment by wuhaohuang** [comment]
> [@wuhaohuang](https://github.com/wuhaohuang) what’s in the node_modules/lefthook? Ideally it should have the following:
> 
> ```
> tree node_modules
> node_modules
> ├── lefthook
> │   ├── README.md
> │   ├── bin
> │   │   └── index.js
> │   ├── get-exe.js
> │   ├── package.json
> │   ├── postinstall.js
> │   └── schema.json
> └── lefthook-darwin-arm64
>     ├── README.md
>     ├── bin
>     │   └── lefthook <- the binary
>     └── package.json
> ```
> 
> If there’s no `lefthook-darwin-arm64`, could you check if you have
> 
> ```
> omit=optional
> ```
> 
> In your ~/.npmrc?
> 
> Also does this fix the issue: `npm install —include=optional`?
> 
> ### Why?
> `lefthook` NPM package distributes all os+arch packages as optional, so the system installs the one with matching OS and architecture. If you omit an optional packages nothing will be installed.


Neither 13 nor 14 have lefthook-darwin-arm64. And my .npmrc does not have omit=optional.
my .npmrc:
```
auto-install-peers=true

strict-peer-dependencies=false

enable-pre-post-scripts=true

dedupe-peer-dependents=true
```

my project is a pnpm monorepo project.

**Comment by mrexox** [comment]
Oh, I see, it’s pnpm. OK, seems like there’s missing support for pnpm package manager.
For a quick fix I’d recommend to add `lefthook-darwin-arm64` to your devDependencies. I will investigate how this issue could be solved.

**Comment by mrexox** [comment]
@wuhaohuang Does this work? What does it print if not?

```bash
node_modules/lefthook/bin/index.js version
```

——

If it prints errors, could you share the structure of your `node_modules/.pnpm`? Only lefthook-related paths are interesting

**Comment by xqvvu** [comment]
> lefthook-darwin-arm64

The issue still exist and it's work if I add `lefthook-darwin-arm64` to devDependencies

**Comment by wLeeming** [comment]
貌似是镜像源没更新导致的问题,    https://npmmirror.com  镜像源的依赖最新版本还是 1.11.13.   下载不到1.11.14 所以报错.   去镜像源里面同步一下最新版本就好了.
